<?php
$event = [
    'id' => 'evt1',
    'posId' => 'pos1',
    'externalNumber' => null,
    'organizationId' => 'org1',
    'timestamp' => 0,
    'creationStatus' => 'Success',
    'errorInfo' => null,
    'order' => [
        'parentDeliveryId' => null,
        'customer' => ['type' => 'one-time', 'name' => 'Cust'],
        'phone' => '123',
        'deliveryPoint' => null,
        'status' => 'Closed',
        'cancelInfo' => null,
        'courierInfo' => null,
        'completeBefore' => null,
        'whenCreated' => null,
        'whenConfirmed' => null,
        'whenPrinted' => null,
        'whenCookingCompleted' => null,
        'whenSended' => null,
        'whenDelivered' => null,
        'comment' => null,
        'problem' => null,
        'operator' => null,
        'marketingSource' => null,
        'deliveryDuration' => 0,
        'indexInCourierRoute' => null,
        'cookingStartTime' => '2024-01-01 00:00:00',
        'isDeleted' => false,
        'whenReceivedByApi' => null,
        'whenReceivedFromFront' => '2024-01-01 00:00:00',
        'movedFromDeliveryId' => null,
        'movedFromTerminalGroupId' => null,
        'movedFromOrganizationId' => null,
        'externalCourierService' => null,
        'movedToDeliveryId' => null,
        'movedToTerminalGroupId' => null,
        'movedToOrganizationId' => null,
        'menuId' => null,
        'deliveryZone' => null,
        'estimatedTime' => null,
        'whenPacked' => null,
        'sum' => 100,
        'number' => 1,
        'sourceKey' => 'default',
        'whenBillPrinted' => null,
        'whenClosed' => null,
        'conception' => null,
        'guestsInfo' => ['count' => 1, 'splitBetweenPersons' => false],
        'items' => [
            [
                'type' => 'Product',
                'product' => ['id' => 'item1', 'name' => 'Item1'],
                'modifiers' => [
                    [
                        'product' => ['id' => 'mod1', 'name' => 'Modifier1'],
                        'amount' => 1,
                        'amountIndependentOfParentAmount' => false,
                        'productGroup' => ['id' => 'pg1', 'name' => 'Group1'],
                        'price' => 0,
                        'pricePredefined' => true,
                        'resultSum' => 0,
                        'positionId' => 'm1',
                        'defaultAmount' => 0,
                        'hideIfDefaultAmount' => false,
                        'freeOfChargeAmount' => 0,
                    ],
                ],
                'price' => 100,
                'cost' => 100,
                'pricePredefined' => true,
                'positionId' => 'p1',
                'resultSum' => 100,
                'status' => 'Added',
                'deleted' => null,
                'amount' => 1,
                'comment' => null,
                'whenPrinted' => null,
                'size' => null,
                'comboInformation' => null,
            ],
        ],
        'combos' => [],
        'payments' => [],
        'tips' => [],
        'discounts' => [],
        'orderType' => ['id' => 'ot1', 'name' => 'OT', 'orderServiceType' => 'DeliveryByClient'],
        'terminalGroupId' => 'tg1',
        'processedPaymentsSum' => 100,
        'loyaltyInfo' => ['coupon' => null, 'appliedManualConditions' => null],
        'externalData' => null,
    ],
];
return $event;
